var config = {
	"Jivox": [
		{ label: "Jivox Mail-Inbox", link: "http://www.google.com/" },
		{ label: "Google Calender", link: "https://calendar.google.com/calendar/b/2/r?tab=mc" },
		{ label: "Jivox Okta Home", link: "https://jivox.okta.com/app/UserHome" },
		{ label: "Jivox HR Portal", link: "https://jivox.keka.com/" },
	],
	"Eng - QA": [
		{ label: "Eng Qa1", link: 'https://jvx.app.qa1.jivox.com/login.html' },
		{ label: "Eng Qa2", link: 'https://jvx.app.qa2.jivox.com/login.html' },
		{ label: "Eng Qa3", link: 'https://jvx.app.qa3.jivox.com/login.html' },
		{ label: "Eng Qa4", link: 'https://jvx.app.qa4.jivox.com/login.html' },
		{ label: "Eng Qa5", link: 'https://jvx.app.qa5.jivox.com/login.html' },
		{ label: "QA Auto1", link: 'https://jvx.app.qa-auto1.jivox.com/login.html' },
		{ label: "QA Auto2", link: 'https://jvx.app.qa-auto2.jivox.com/login.html' },
		{ label: "QA Auto3", link: 'https://jvx.app.qa-auto3.jivox.com/login.html' },
		{ label: "QA Auto4", link: 'https://jvx.app.qa-auto4.jivox.com/login.html' },
		{ label: "QA Auto5", link: 'https://jvx.app.qa-auto5.jivox.com/login.html' },
		{ label: "QA Auto6", link: 'https://jvx.app.qa-auto6.jivox.com/login.html' },
		{ label: "QA Auto6", link: 'https://jvx.app.qa-auto6.jivox.com/login.html' },
		{ label: "QA Beta", link: 'https://jvx.app.beta.jivox.com/login.html' },
		{ label: "My Bugs", link: 'https://jivox1.atlassian.net/jira/dashboards/10500?maximized=10702' },
		{ label: "Bitbucket", link: 'https://bitbucket.org/dashboard/overview' },
		{ label: "Jenkins", link: 'https://jenkins-ci.jivox.com/' },
		{ label: "Jivox Confluence", link: 'https://jivox1.atlassian.net/wiki/home' },
		{ label: "Jivox Asana", link: 'https://app.asana.com/0/home/1200476345619580' },
		{ label: "Katta-WSR", link: 'https://docs.google.com/document/d/1BXzX2QFY-6JlqqwqRUZzuYgsvIgzzmE70SdAkwoCuRI/edit#heading=h.yssmpaub246f' },
		{ label: "Eng QA Helping Doc", link: 'https://docs.google.com/spreadsheets/d/1cDfjiGRStVPWVh0xyLL_rUxna8rzr3SM5BvUNyqsmMs/edit#gid=1846387443' },
	],
	"Production US/EU": [
		{ label: "Jivox Product Login - US", link: 'https://jvx.app.jivox.com/login.html' },
		{ label: "Jivox Product Login - EU", link: 'https://jvx.app.euw1.jivox.com/login.html' },
		{ label: "Jivox Product Login - Beta", link: 'https://jvx.app.beta.jivox.com/login.html' },
		{ label: "Stage Jivox Login Live", link: 'https://jvx.stage.app.jivox.com/login.html' },
		{ label: "Jivox Asana", link: 'https://app.asana.com/0/1198886458926888/calendar' },
		{ label: "Jivox Admin Portal", link: 'https://slate.jivox.com/jivox/admin/pixel/editPixel.php' },
		{ label: "RHS Expression Status", link: 'https://jenkins.euw1.jivox.com/job/RHS%20EXP%20UPDATE/build?delay=0sec' },
		{ label: "DataLogs", link: 'https://app.datadoghq.com/dashboard/lists' },
		{ label: "AWS SAML", link: 'https://d-90676720e7.awsapps.com/start#/' },
		{ label: "Pre-Pod Trafficker UP/Down", link: 'https://jenkins.euw1.jivox.com/view/Activities/job/preprod-show-conf/build?delay=0sec' },
		{ label: "Snowflakecomputing", link: 'https://jivoxanalytics.us-east-1.snowflakecomputing.com/console#/internal/worksheet' },
		{ label: "Product Documentations", link: 'https://docs.jivox.com/' },
		{ label: "Product Expert Rotation", link: 'https://docs.google.com/spreadsheets/d/1w5J-ppW9K0Kto9B0OKh9IOFJzHYfhGRAgX75VOE4h3s/edit#gid=1237105473' },
		{ label: "Platform Defaults hourly Monitors", link: 'https://docs.google.com/spreadsheets/d/123z2vrwUBQ_kytlwBIYZHD-_CzFDbHiqsfjZKQERP_0/edit#gid=16877236' },
	],
	"Documentations": [
		{ label: "CS - JIRA ", link: 'https://jivox1.atlassian.net/jira/dashboards/10500?maximized=10902' },
		{ label: "CSQA Assignment Sheet", link: 'https://docs.google.com/spreadsheets/d/124e6Low3oYpm6dCrkysgbtBmwHfZeZC4JT4CmhGKUuc/edit#gid=1881898682/' },
		{ label: "CSQA Track Record", link: 'https://docs.google.com/spreadsheets/d/1C307-kPIPtlhaVIgPw3PD8agFx_IdiKknzvIWB7cQ1k/edit#gid=1031084935' },
		{ label: "CSQA Check List", link: 'https://docs.google.com/spreadsheets/d/1xoTPFSQ9eZUQbYwMzFTwKNz4Up84vpX0uoSeMeM118c/edit#gid=743790007' },
		{ label: "Campaign Issue's Report", link: 'https://docs.google.com/spreadsheets/d/1gPtRW4MtfdvOvNaBKyObgEvkA7yPqZ8qnjx0bDsCX10/edit#gid=6945593' },
		{ label: "CS - Accounts over view ", link: 'https://docs.google.com/spreadsheets/d/1kfnRgF2lH1ZNpOB-a7AjJhYKiemILtOuBcgrzZRKpO8/edit#gid=0' },
		{ label: "Default value of Campaigns", link: 'https://docs.google.com/spreadsheets/d/1ReHrKzc6DVwgvXBizrMAegBCkKFHuLrNRb5SB3JcpNY/edit#gid=23998677' },
		{ label: "CS - Resource Projection ", link: 'https://docs.google.com/spreadsheets/d/1TiunQc1gzPOxB3JcGNrElopP1iGWzeTe6imeoNt6ZSM/edit#gid=488453468' },
		{ label: "Campaign OverNight Sheet", link: 'https://docs.google.com/spreadsheets/d/1xvEJtUz2fDz8bmESMoopXmMkj4PgwmAwaxVA9SaEkyI/edit?pli=1#gid=21/' },
		{ label: "ComPay and NSA", link: 'https://docs.google.com/spreadsheets/d/1RUQARB5__yW_di8vRr1eyNsCXI_V-Eh3KjZJRQ8n8rY/edit#gid=666452893' },
		{ label: "CS Holiday List 2022", link: 'https://docs.google.com/spreadsheets/d/1yHmqqhl_zbHQMCqxewkS9c1BG-rWV5PirkGSwC65s-o/edit#gid=2085200202' },
		{ label: "CSQA Documentations ", link: 'https://docs.google.com/spreadsheets/d/1zwkkEyrdrGsFGK5H6Znxk9yQtAhbAUdseBncGXX9rr0/edit#gid=0' },
		{ label: "Knowing Backend Parameters ", link: 'https://as.jivox.com/jivox/utils/getParamsInfo_x.php?campaignId=103943&siteId=34f95fc965694c&pid=IK7xKP' },
		{ label: "Live Campaign Tags ", link: 'https://docs.google.com/spreadsheets/d/1_z2xnY2Ij2sO90nla0PdR8-0ATwsbw6DwaM9EIiE8iE/edit#gid=2040755410' },
		{ label: "External Parameters in Jivox", link: 'https://docs.google.com/spreadsheets/d/1APsSP_doHYWCP7tzwEZL0ABzJ-T7wtUacHSU7jamJIM/edit#gid=0' },
	],
	"Tags Validators": [
		{ label: "GAP/WSI/Signet", link: 'https://docs.google.com/spreadsheets/d/1QD16uT-ID6gu7IlmsVZtJZFssfL4mPmjHAB7UO_IdPM/edit#gid=0' },
		{ label: "New tag rocket ", link: 'https://qa64.jivox.com/newtagrocket_v1/' },
		{ label: "Jivox Vast / VPaid Validator", link: 'https://slate.jivox.com/VAST/test.php#' },
		{ label: "Xaxis Vast/Vpaid Test player", link: 'https://xal.rocks/sandbox/lisa/vast/' },
		{ label: "Jivox API's ", link: 'https://api-docs.jivox.com/swagger/' },
		{ label: "Cookie Data", link: 'https://traffick.jivox.com/jivox/serverAPIs/resolveDynamicData.php?var=cookieData:cookieData&campaignId=148804' },
		{ label: "Decision Graph Preview", link: 'https://slate.jivox.com/studio/previewSegmentsTree.php?campaignId=155328&versionId=0' },
		{ label: "Knowing Geo Location", link: 'https://traffick.jivox.com/jivox/serverAPIs/resolveDynamicData.php?var=geo:geo' },
		{ label: "Knowing Weather Details", link: 'https://traffick.jivox.com/jivox/serverAPIs/resolveDynamicData.php?var=weather:weather' },
		{ label: "Knowing API breezometer", link: 'https://slate.jivox.com/studio/previewSegmentsTree.php?campaignId=155328&versionId=0' },
		{ label: "JW Player", link: 'https://developer.jwplayer.com/tools/ad-tester/' },
	],
	"Campaigns Related": [
		{ label: "CSQA CTC", link: 'https://docs.google.com/spreadsheets/d/1R9OCvtRp00B-clUXyJX0RBqJAeTePT-bVm-rc_7CsoM/edit#gid=1196903107' }
	],
	"Learning tasks": [
		{ label: "SDET Onboarding", link: 'https://www.knowonlineadvertising.com/' },
		{ label: "About online adverting", link: 'https://docs.google.com/spreadsheets/d/1Y0aGrMQiNYJd29ZYlmlY6L1cVNXEfn9l9H0X5MiWz7Q/edit#gid=0' },
	],
}